# -*- coding: utf-8 -*-
"""23201003_Masrur Sarar_CSE440_Sec-3_Lab-1_AssignmentNo-1_Spring2026

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v3RRL8En_RGRp25hMPcR7A3Wzx3bFMeD
"""

!pip install nltk

import nltk
import string
import numpy as np
import matplotlib.pyplot as plt
from nltk.corpus import gutenberg, webtext, stopwords, reuters, movie_reviews, state_union
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.stem import LancasterStemmer, PorterStemmer, SnowballStemmer, WordNetLemmatizer
from nltk import pos_tag
from nltk.probability import FreqDist
from nltk.util import ngrams
from wordcloud import WordCloud

nltk.download('all')
nltk.download('punkt_tab')

display(gutenberg.fileids())
display(webtext.fileids())
print(stopwords.words('english')) #glue words, carry little to no unique meaning,
                                  #Stopwords='stop' processing highly frequent low-value 'words' to save storage space and processing time

#Stemming- chops off end of word (suffixes and prefixes). Fast
#Lemmatization- morphological analysis of word,context,part of speech (lemma).High accuracy, preserves meaning
#ngrams- sequence of n items(words,letters or syllables), bigrams and trigrams are better. not to lose context

#Task-1
import nltk
from nltk.corpus import reuters, movie_reviews
display(reuters.categories())
display(movie_reviews.fileids())

#Task-2
import nltk
import matplotlib.pyplot as plt
from wordcloud import WordCloud
from nltk.corpus import state_union
from nltk.tokenize import word_tokenize
from nltk.probability import FreqDist

su_a=state_union.fileids()[0]
su_b=state_union.fileids()[-1]

file_a = state_union.raw(su_a)
file_b = state_union.raw(su_b)

file1 = word_tokenize(file_a)
file2 = word_tokenize(file_b)

fd1 = FreqDist(file1)
fd2 = FreqDist(file2)

wc1 = WordCloud(width=1000, height=600, background_color='white')
cloud1 = wc1.generate_from_frequencies(fd1)

wc2 = WordCloud(width=1000, height=600, background_color='white')
cloud2 = wc2.generate_from_frequencies(fd2)

plt.figure(figsize = (20,10))

plt.subplot(1, 2, 1)
plt.imshow(cloud1)
plt.axis('off')
plt.title(f"Word Cloud - {su_a}")

plt.subplot(1, 2, 2)
plt.imshow(cloud2)
plt.axis('off')
plt.title(f"Word Cloud - {su_b}")

plt.tight_layout()
plt.show()

#Task-3
import nltk
import matplotlib.pyplot as plt
from nltk.corpus import stopwords
from nltk.corpus import movie_reviews
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.probability import FreqDist

text = movie_reviews.raw(movie_reviews.fileids(categories=['neg'])[1])
t_text = word_tokenize(text)

stop_words = stopwords.words('english')
filtered_words = []
for w in t_text:
  if w.lower() not in stop_words:
    filtered_words.append(w.lower())

lemmatizer = WordNetLemmatizer()
lemmatized_word = []
for word in filtered_words:
  lemmatized_word.append(lemmatizer.lemmatize(word))

word_count = FreqDist(lemmatized_word)
word = []
count = []
for tup in word_count.most_common(20):
  word.append(tup[0])
  count.append(tup[1])
print(word)
print(count)

plt.bar(word,count)
plt.xticks(rotation=90)
plt.title("20 most frequent words")
plt.show()

#Task-4
import nltk
import string
import numpy as np
from nltk.corpus import reuters
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.probability import FreqDist
from nltk.util import ngrams

text=reuters.raw(reuters.fileids()[0])

text_low=text.lower()

text_low_nopun = text_low.translate(str.maketrans('', '', string.punctuation))
#no_pun = []
#for w in words: if w.lower() not in string.punctuation: no_pun.append(w)

words = word_tokenize(text_low_nopun)

stop_words = stopwords.words('english')
filtered_words = []
for w in words:
  if w.lower() not in stop_words:
    filtered_words.append(w)

word_count = FreqDist(filtered_words)
word = []
count = []
for tup in word_count.most_common(12):
  word.append(tup[0])
  count.append(tup[1])

bigrams = list(ngrams(filtered_words, n = 2))


matrix = np.zeros((len(word), len(word)), dtype=int)

word_to_index = {}

for i, w in enumerate(word):
    word_to_index[w] = i

print(word_to_index)

for i,j in bigrams:
  if i in word and j in word:
    matrix[word_to_index[i], word_to_index[j]] += 1

print(matrix)

#Task-5
import nltk
from nltk.corpus import udhr
from nltk.tokenize import word_tokenize
from nltk.probability import FreqDist
from nltk.util import ngrams

#udhr.fileids()
text=udhr.raw('German_Deutsch-Latin1')
words = word_tokenize(text)


vowel = ['a','e','i','o','u','ä','ö','ü']
filtered_words = []
for w in words:
  sv=[]
  for v in w:
    if v.lower() in vowel:
      sv.append(v.lower())
  if len(sv)>=3:
    trigrams = list(ngrams(sv, 3))
    filtered_words.extend(trigrams)


word_count = FreqDist(filtered_words)
sorted_list = word_count.most_common()
sorted_list
#word = []
#count = []
#for tup in word_count:
#  word.append(tup[0])
#  count.append(tup[1])
#plt.bar(word,count)
